### ISSUE TITLE
Instructions incorrect

### ISSUE THREAD

**Issue by kenmcc** [PaulDFoster/MultitechConduitModule#1]
Hi,
I've been sent to this page by a contact in Multitech, as a reference point for some work we're doing.

I tried following the instructions on the Readme.md :

> "Run the IoT Edge solution by executing the iotedge_device_cloud_upload_sample with a parameter..."

but that file is missing in the current version; reverting to version 590679d presents this file in the history, but running that errors with 

>./iotedge_device_cloud_upload_sample: error while loading shared libraries: libgateway.so: cannot open shared object file: No such file or directory

I can't find that file anywhere in the repository.

**Comment by PaulDFoster** [comment]
Hi,

Yes you are quite correct. The referenced executable is part of the IoT Edge V1 samples. I have however, placed the same executable in the Bin directory called bridge. 

I recommend you deploy the entire IoT Edge V1 SDK and build the samples to understand the operation of IoT Edge. The supplied bridge executable is only a basic demonstration of deployment and additional functionality is required to have a robust deployment.
